const areas = [
  {
    key: 1,
    id: "1000",
    title: "ÁREA 1000",
    vergeUrl: "applications/1000AltaNueva/1000AltaNueva.html",
    visible: true,
  },
  {
    key: 2,
    id: "2600",
    title: "ÁREA 2000",
    vergeUrl: "applications/2600Chancado01/2600Chancado01.html",
    visible: true,
  },
  {
    key: 3,
    id: "3100/3200",
    title: "ÁREA 3000",
    vergeUrl: "applications/3100molienda/3100molienda.html",
    visible: true,
  },
   {
    key: 4,
    id: "3300",
    title: "ÁREA 3300",
    vergeUrl: "applications/3300Flotacion/3300Flotacion.html",
    visible: true,
  },/*
  {
    key: 5,
    id: "3400",
    title: "Planta de molibdeno",
    vergeUrl: "applications/area_3400/area_3400.html",
    visible: true,
  },
  {
    key: 6,
    id: "3600",
    title: "Espesamiento, filtrado, almacenamiento de concentrado de Cu",
    vergeUrl:
      "applications/3600_espesamiento_concentrado/3600_espesamiento_concentrado.html",
    visible: true,
  }, 
  {
    key: 7,
    id: "3700",
    title: "ÁREA 4000",
    vergeUrl: "applications/4000Relaves/4000Relaves.html",
    visible: true,
  },
  {
    key: 8,
    id: "3500",
    title: "Planta de cal y reactivos",
    visible: true,
  }, */
 /*  {
    key: 8,
    id: "3500",
    title: "Área 3510 Planta de Cal",
    visible: true,
  },
  {
    key: 9,
    id: "3900",
    title: "Utilitarios",
    visible: true,
  },*/
  {
    key: 10,
    id: "4000",
    title: "ÁREA 4000",
      vergeUrl: "applications/4000Relaves/4000Relaves.html",
    visible: true,
  }, 
  {
    key: 11,
    id: "5000",
    title: "ÁREA 5800",
    vergeUrl: "applications/5000Puerto/5000Puerto.html",
    visible: true,
  },
];

const subareas = [
  {
    key: 1,
    id: "cam-pica-rocas",
    locationId: "operador-pica-roca",
    title: "Chancadora Primaria 1 y 2 ",
    visible: true,
    idArea: "2600",
  },
  {
    key: 2,
    id: "cam-fajas-alimentadoras",
    locationId: "operador-fajas-alimentadoras",
    title: "Chute Alimentación 1 y 2 ",
    visible: true,
    idArea: "2600",
  },
  {
    key: 3,
    id: "cam-fajas-sacrificio",
    locationId: "operador-faja-sacrificio",
    title: "Faja Transportadora de Sacrificio ",
    visible: true,
    idArea: "2600",
  },
 /*  {
    key: 4,
    id: "cam-supresor-polvo",
    locationId: "operador-supresor-polvo",
    title: "Sis. Supresor de polvo",
    visible: true,
    idArea: "2600",
  },
  {
    key: 5,
    id: "cam-colector-polvo",
    locationId: "operador-colector-polvo",
    title: "Sis. Colector de polvo",
    visible: true,
    idArea: "2600",
  }, */
  {
    key: 4,
    id: "cam-rompe-rocas",
    locationId: "operador-supresor-polvo",
    title: "Rompe Rocas 1 y 2 ",
    visible: true,
    idArea: "2600",
  },
  {
    key: 5,
    id: "cam-tolva-recepcion",
    locationId: "operador-colector-polvo",
    title: "Tolva de recepción 1 y 2 ",
    visible: true,
    idArea: "2600",
  },
  {
    key: 6,
    id: "cam-faja-overland",
    locationId: "operador-faja-overland",
    title: "Faja transportadora overland ",
    visible: true,
    idArea: "2600",
  },
  /*  {
    key: 6,
    id: "cam-faja-overland",
    locationId: "operador-faja-overland",
    title: "Faja transportadora overland 1",
    visible: true,
    idArea: "2600",
  }, */
 /*  {
    key: 7,
    id: "cam-faja-overland-2",
    locationId: "operador-faja-overland-2",
    title: "Faja transportadora overland 2",
    visible: true,
    idArea: "2600",
  }, */
 /*  {
    key: 8,
    id: "cam-alimentadores",
    locationId: "operador-alimentadores",
    title: "Fajas Alimentadoras de Recuperación de Grueso",
    visible: true,
    idArea: "3100/3200",
  }, */
  {
    key: 9,
    id: "cam-colectores",
    locationId: "operador-colectores",
    title: "Fajas Transportadoras Alimentación Molinos SAG 1 y 2",
    visible: true,
    idArea: "3100/3200",
  },
  {
    key: 10,
    id: "cam-molinos",
    locationId: "operador-molinos",
    title: "Molino SAG 1 y 2",
    visible: true,
    idArea: "3100/3200",
  },
  // {
  //   key: 11,
  //   id: 'cam-hidrociclones',
  //   locationId: 'operador-hidrociclones',
  //   title: 'Bombas Alimentación Nidos Hidrociclones',
  //   visible: true,
  //   idArea: '3100/3200'
  // },
  {
    key: 12,
    id: "cam-transportadora",
    locationId: "operador-transportadoras",
    title: "Fajas Transportadoras de Alta Pendiente ",
    visible: true,
    idArea: "3100/3200",
  },
  {
    key: 13,
    id: "cam-faja-silo-pebble",
    locationId: "operador-faja-silo-pebble",
    title: "FAJA TRANSPORTADORA DISTRIBUCIÓN SILO PEBBLE",
    visible: true,
    idArea: "3100/3200",
  },
  {
    key: 14,
    id: "cam-alimentador-chancador",
    locationId: "operador-faja-chancadora",
    title: "Faja alimentadora chancadora Pebble 1",
    visible: true,
    idArea: "3100/3200",
  },
  /* {
    key: 15,
    id: "cam-alimentador-chancador-2",
    locationId: "operador-faja-chancadora-2",
    title: "Faja Alimentadora Chancadora Pebble 2",
    visible: true,
    idArea: "3100/3200",
  }, */
  {
    key: 16,
    id: "cam-chancadora",
    locationId: "operador-chancadora",
    title: "Chancadora de Pebbles ",
    visible: true,
    idArea: "3100/3200",
  },
 /*  {
    key: 17,
    id: "cam-fajas",
    locationId: "operador-fajas",
    title: "Faja Transportadora Pebble Retorno",
    visible: true,
    idArea: "3100/3200",
  }, */
  {
    key: 18,
    id: "cam-hidrociclones",
    locationId: "operador-hidrociclones",
    title: "Nido de Hidrociclones ",
    visible: true,
    idArea: "3100/3200",
  },
  {
    key: 18,
    id: "cam-alimentadores",
    locationId: "operador-alimentadores",
    title: "Molino de bolas",
    visible: true,
    idArea: "3100/3200",
  },
  {
    key: 19,
    id: "cam-muestreador-metalurgico-alimentacion",
    locationId: "operador-muestreador-metalurgico-alimentacion",
    title: "Celdas columna",
    visible: true,
    idArea: "3300",
  },
  {
    key: 20,
    id: "cam-celdas-rougher",
    locationId: "operador-celdas-rougher",
    title: "Flotación colectiva (Celdas) Área 3310",
    visible: true,
    idArea: "3300",
  },
  // {
  //   key: 21,
  //   id: 'cam-002',
  //   locationId: 'operador-002',
  //   title: 'Celdas Primera Limpieza Fila 1 y 2',
  //   visible: true,
  //   idArea: '3300'
  // },
  {
    key: 22,
    id: "cam-bombas-alimentacion",
    locationId: "operador-bombas-alimentacion",
    title: "Sopladores Flotación colectiva",
    visible: true,
    idArea: "3300",
  },
  {
    key: 23,
    id: "cam-segunda-limpieza-cobre",
    locationId: "operador-segunda-limpieza-cobre",
    title: "Molinos verticales de remolienda ",
    visible: true,
    idArea: "3300",
  },
  /* {
    key: 24,
    id: "cam-muestreador-metalurgico-concentrado-cu-mo",
    locationId: "operador-muestreador-metalurgico-concentrado-cu-mo",
    title: "Muestreador Metalúrgico Concentrado Cu-Mo",
    visible: true,
    idArea: "3300",
  }, */
  {
    key: 25,
    id: "cam-nido-hidrociclones",
    locationId: "operador-nido-hidrociclones",
    title: "Nidos de Hidrociclones de Remolienda ",
    visible: true,
    idArea: "3300",
  },
  {
    key: 26,
    id: "cam-tanque-acondicionador",
    locationId: "ubi_3410-TK-001",
    title: "Tanque Acondicionador",
    visible: true,
    idArea: "3400",
  },
  {
    key: 27,
    id: "cam-celdas-flotacion-rougher",
    locationId: "ubi_3410-FT-001@005",
    title: "Celdas Flotacion Rougher",
    visible: true,
    idArea: "3400",
  },
  {
    key: 28,
    id: "cam-celdas-flotacion-limpieza",
    locationId: "ubi_3410-FT-011@014",
    title: "Celdas Flotacion Limpieza",
    visible: true,
    idArea: "3400",
  },
  {
    key: 29,
    id: "cam-celdas-columna-flotacion",
    locationId: "ubi_3410-FT-031/032",
    title: "Celdas Columna Flotacion",
    visible: true,
    idArea: "3400",
  },
  {
    key: 30,
    id: "cam-sistema-lavador-gases",
    locationId: "ubi_3410-SK-003",
    title: "Sistema Lavador de Gases",
    visible: true,
    idArea: "3400",
  },
  {
    key: 31,
    id: "cam-espesador-concentrado-molibdeno",
    locationId: "ubi_3410-TH-001",
    title: "Espesadores de concentrado de molibdeno",
    visible: true,
    idArea: "3400",
  },
  {
    key: 32,
    id: "cam-colector-polvo-tolva",
    locationId: "ubi_3410-BH-001",
    title: "Colector de polvo tolva",
    visible: true,
    idArea: "3400",
  },
  {
    key: 33,
    id: "cam-filtro-concentrado-molibdeno",
    locationId: "ubi_3410-FL-001",
    title: "Filtro de concentrado molibdeno",
    visible: true,
    idArea: "3400",
  },
  {
    key: 34,
    id: "cam-secador-concentrado-molibdeno",
    locationId: "ubi_3410-DR-001",
    title: "Secador concentrado Molibdeno",
    visible: true,
    idArea: "3400",
  },

  {
    key: 35,
    id: "cam-cajon-distribuidor-alimentacion",
    locationId: "operador-cajon-distribuidor-alimentacion",
    title: "Cajón distribuidor alimentación de concentrado",
    visible: true,
    idArea: "3600",
  },
  {
    key: 36,
    id: "cam-bomba-underflow-cu-mo",
    locationId: "operador-bomba-underflow-cu-mo",
    title: "Bombas agua recuperada espesadores",
    visible: true,
    idArea: "3600",
  },
  {
    key: 37,
    id: "cam-cajon-distribuidor-concentrado",
    locationId: "operador-cajon-distribuidor-concentrado",
    title: "Cajón distribuidor de concentrado",
    visible: true,
    idArea: "3600",
  },
  {
    key: 38,
    id: "cam-filtros-concentrado-cu",
    locationId: "operador-filtros-concentrado-cu",
    title: "Filtros de concentrado de CU",
    visible: true,
    idArea: "3600",
  },
  {
    key: 39,
    id: "cam-planta-molibdeno",
    locationId: "operador-planta-molibdeno",
    title: "Bomba de alimentación concentrado planta de molibdeno",
    visible: true,
    idArea: "3600",
  },
  {
    key: 40,
    id: "cam-bomba-sumidero",
    locationId: "operador-bomba-sumidero",
    title: "Bomba sumidero planta filtro",
    visible: true,
    idArea: "3600",
  },
  {
    key: 41,
    id: "cam-recirculacion-agua",
    locationId: "operador-recirculacion-agua",
    title: "Tanque de recirculación de agua de filtrado",
    visible: true,
    idArea: "3600",
  },

  {
    key: 42,
    id: "cam-muestreador-metalurgico",
    locationId: "operador-muestreador-metalurgico",
    title: "Muestreador metalúrgico colas globales",
    visible: true,
    idArea: "3700",
  },
  {
    key: 43,
    id: "",
    locationId: "",
    title: "Cajón distribución de relaves",
    visible: false,
    idArea: "3700",
  },
  {
    key: 44,
    id: "cam-espesador-relaves-1",
    locationId: "operador-espesador-relaves-1",
    title: "espesador de relaves 1",
    visible: true,
    idArea: "3700",
  },
  {
    key: 45,
    id: "cam-espesador-relaves-2",
    locationId: "operador-espesador-relaves-2",
    title: "espesador de relaves 2",
    visible: true,
    idArea: "3700",
  },
  {
    key: 46,
    id: "cam-bomba-recirculacion",
    locationId: "operador-bomba-recirculacion",
    title: "Bombas de recirculación",
    visible: true,
    idArea: "3700",
  },
  {
    key: 47,
    id: "cam-bombas-agua-procesos",
    locationId: "operador-bombas-agua-procesos",
    title: "Bombas agua de procesos",
    visible: true,
    idArea: "3700",
  },

  {
    key: 48,
    id: "3500-3300",
    locationId: "applications/Area_3300/index.html?area=3500",
    title: "Equipos ubicados en el area 3300",
    visible: true,
    idArea: "3500",
  },
  {
    key: 49,
    id: "3500-3400",
    locationId: "applications/area_3400/area_3400.html?area=3500",
    title: "Equipos ubicados en el area 3400",
    visible: true,
    idArea: "3500",
  },
/*   {
    key: 50,
    id: "3500-3700",
    locationId: "applications/area_3700/area_3700.html?area=3500",
    title: "Equipos ubicados en el area 3700",
    visible: true,
    idArea: "3500",
  }, */
  {
    key: 50,
    id: "3500-3700",
    locationId: "applications/area_3700/area_3700.html?area=3500",
    title: "AREA  3520 REACTIVOS DE FLOTACION Y PLANTA DE FLOCULANTE",
    visible: true,
    idArea: "3500",
  },

  {
    key: 51,
    id: "3900-3300",
    locationId: "applications/Area_3300/index.html?area=3900",
    title: "Equipos ubicados en el area 3300",
    visible: true,
    idArea: "3900",
  },
  {
    key: 52,
    id: "3900-3700",
    locationId: "applications/area_3700/area_3700.html?area=3900",
    title: "Equipos ubicados en el area 3700",
    visible: true,
    idArea: "3900",
  },
  {
    key: 53,
    id: "cam-torre-captacion-1",
    locationId: "operador-torre-captacion-1",
    title: "Torre de captación N° 1",
    visible: true,
    idArea: "4000",
  },
  {
    key: 54,
    id: "cam-torre-captacion-2",
    locationId: "operador-torre-captacion-2",
    title: "Torre de captación N° 2",
    visible: true,
    idArea: "4000",
  },
  {
    key: 55,
    id: "cam-torre-captacion-3",
    locationId: "operador-torre-captacion-3",
    title: "Torre de captación N° 3",
    visible: true,
    idArea: "4000",
  },
  {
    key: 56,
    id: "cam-carga-hidrociclon",
    locationId: "operador-carga-hidrociclon",
    title: "Cajón de carga hidrociclones",
    visible: true,
    idArea: "4000",
  },
  {
    key: 57,
    id: "cam-nidos-hidrociclones-primera-etapa",
    locationId: "operador-nidos-hidrociclones-primera-etapa",
    title: "Nidos de hidrociclones primera etapa",
    visible: true,
    idArea: "4000",
  },
 /*  {
    key: 58,
    id: "cam-cajon-descarga-hidrociclones",
    locationId: "operador-cajon-descarga-hidrociclones",
    title: "Cajón de descarga de hidrociclones",
    visible: true,
    idArea: "4000",
  }, */
   {
    key: 58,
    id: "cam-cajon-descarga-hidrociclones",
    locationId: "operador-cajon-descarga-hidrociclones",
    title: "Cajón de Lamas Primera Etapa de Hidrociclones",
    visible: true,
    idArea: "4000",
  },
  {
    key: 59,
    id: "cam-nidos-hidrociclones-segunda-etapa",
    locationId: "operador-nidos-hidrociclones-segunda-etapa",
    title: "Nidos de hidrociclones de segunda etapa",
    visible: true,
    idArea: "4000",
  },
  {
    key: 60,
    id: "cam-cajones-descarga-segunda-etapa",
    locationId: "operador-cajones-descarga-segunda-etapa",
    title: "Cajones de descarga de segunda etapa",
    visible: true,
    idArea: "4000",
  },
  {
    key: 61,
    id: "cam-estacion-intermedia",
    locationId: "operador-estacion-intermedia",
    title: "Estación intermedia",
    visible: true,
    idArea: "4000",
  },
  {
    key: 62,
    id: "cam-presa-vizcachas",
    locationId: "operador-presa-vizcachas",
    title: "ESTACIÓN DE BOMBEO - PRESA VIZCACHAS",
    visible: true,
    idArea: "1000",
  },
  {
    key: 63,
    id: "cam-titire",
    locationId: "operador-titire",
    title: "BOCATOMA TITIRE",
    visible: true,
    idArea: "1000",
  },
 
  {
    key: 64,
    id: "cam-faja-alimentadora",
    locationId: "operador-faja-alimentadora",
    title: "Faja receptora de concentrado",
    visible: true,
    idArea: "5000",
  },
  {
    key: 65,
    id: "cam-faja-receptora-concentrado",
    locationId: "operador-faja-receptora-concentrado",
    title: "Tanque agua potable ",
    visible: true,
    idArea: "5000",
  },
  {
    key: 66,
    id: "cam-faja-recuperacion-concentrado",
    locationId: "operador-faja-recuperacion-concentrado",
    title: "Tanque agua fresca ",
    visible: true,
    idArea: "5000",
  },
  {
    key: 67,
    id: "cam-faja-tubular-receptora",
    locationId: "operador-faja-tubular-receptora",
    title: "Faja Tubular Recup. de Concentrado ",
    visible: true,
    idArea: "5000",
  },
  {
    key: 68,
    id: "cam-faja-tubular-muelle",
    locationId: "operador-faja-tubular-muelle",
    title: "Tanque agua proceso - Red de Incendio ",
    visible: true,
    idArea: "5000",
  },
  {
    key: 69,
    id: "cam-cargador-radial-barco",
    locationId: "operador-cargador-radial-barco",
    title: "Edificio almacenamiento concentrado",
    visible: true,
    idArea: "5000",
  },
  {
    key: 70,
    id: "5000-sala-electrica",
    locationId: "operador-cargador-radial-barco",
    title: "Sala eléctrica - Instalaciones del Puerto ",
    visible: true,
    idArea: "5000",
  },
  {
    key: 71,
    id: "5000-faja-tubular-muelle",
    locationId: "operador-cargador-radial-barco",
    title: "Faja Tubular Muelle",
    visible: true,
    idArea: "5000",
  },
  {
    key: 72,
    id: "5000-bodegas-nave",
    locationId: "operador-cargador-radial-barco",
    title: "Bodegas de Nave",
    visible: true,
    idArea: "5000",
  },
  /*   {
    key: 70,
    id: "cam-fajas",
    locationId: "operador-fajas",
    title: "Faja Transportadora Recuperación Pebble",
    visible: true,
    idArea: "3100/3200",
  }, */
];

const subSubAreas = [
  {
    key: 1,
    id: "cam-colector-polvo-silo-cal",
    locationId: "operador-colector-polvo-silo-cal",
    title: "Colectores de Polvo Silo de Cal",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 2,
    id: "cam-nido-hidrociclones-planta-lechada",
    locationId: "operador-nido-hidrociclones-planta-lechada",
    title: "Molino Vertical Planta Lechada de Cal",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 3,
    id: "cam-molino-vertical-planta-lechada",
    locationId: "operador-molino-vertical-planta-lechada",
    title: "Tanque Traspaso Planta Lechada de Cal",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 4,
    id: "cam-bombas-lechada-cal",
    locationId: "operador-bombas-lechada-cal",
    title: "Nido de Hidrociclones Planta Lechada de Cal",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 5,
    id: "cam-tanque-traspaso-planta-lechada",
    locationId: "operador-tanque-traspaso-planta-lechada",
    title: "Tanque 1 y 2 Almacenamiento Lechada de Cal",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 6,
    id: "cam-tanque-almacenamiento-lechada",
    locationId: "operador-tanque-almacenamiento-lechada",
    title: "Bombas Lechada de Cal",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 7,
    id: "cam-colector-polvo-colector-2",
    locationId: "operador-colector-polvo-colector-2",
    title: "Tanque Lechada de Cal Planta Molibdeno",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 8,
    id: "cam-bomba-descarga-espumante-1",
    locationId: "operador-bomba-descarga-espumante-1",
    title: "Bomba Lechada de Cal Planta Molibdeno",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 9,
    id: "cam-bomba-descarga-espumante-2",
    locationId: "operador-bomba-descarga-espumante-2",
    title: "Colector de Polvo Colector 2",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 10,
    id: "cam-bomba-descarga-colector-3",
    locationId: "operador-bomba-descarga-colector-3",
    title: "Tanque Mezclador Colector 2",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 11,
    id: "cam-bomba-transferencia-colector-3-espumante-2",
    locationId: "operador-bomba-transferencia-colector-3-espumante-2",
    title: "Bomba Transferencia Colector 2",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 12,
    id: "cam-bomba-descarga-diesel-planta-concentradora",
    locationId: "operador-bomba-descarga-diesel-planta-concentradora",
    title: "Bombas Dosificadoras Colector 2",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 13,
    id: "cam-bomba-transferencia-diesel-planta-concentradora",
    locationId: "operador-bomba-transferencia-diesel-planta-concentradora",
    title: "Bomba Descarga Diésel Planta Concentradora",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 14,
    id: "cam-tanque-mezclador-colector-2",
    locationId: "operador-tanque-mezclador-colector-2",
    title: "Bomba Transferencia Diésel Planta Concentradora",
    visible: true,
    idArea: "3500-3300",
  },
  {
    key: 15,
    id: "cam-bomba-descarga-diesel-planta-molibdeno",
    locationId: "operador-bomba-descarga-diesel-planta-molibdeno",
    title: "Bomba descarga de diésel planta molibdeno",
    visible: true,
    idArea: "3500-3400",
  },
  {
    key: 16,
    id: "cam-bomba-descarga-nahs",
    locationId: "operador-bomba-descarga-nahs",
    title: "Bomba descarga NaHS",
    visible: true,
    idArea: "3500-3400",
  },
  {
    key: 17,
    id: "cam-bomba-transferencia-nahs",
    locationId: "operador-bomba-transferencia-nahs",
    title: "Bomba transferencia NaHS",
    visible: true,
    idArea: "3500-3400",
  },
  {
    key: 18,
    id: "cam-bomba-circuito-nahs",
    locationId: "operador-bomba-circuito-nahs",
    title: "Bomba circuito NaHS",
    visible: true,
    idArea: "3500-3400",
  },
  {
    key: 19,
    id: "cam-tanque-diario-nahs",
    locationId: "operador-tanque-diario-nahs",
    title: "Tanque diario NaHS",
    visible: true,
    idArea: "3500-3400",
  },
  {
    key: 20,
    id: "cam-tolvas-almacenamiento-floculante",
    locationId: "operador-tolvas-almacenamiento-floculante",
    title: "Colector de polvo",
    visible: true,
    idArea: "3500-3700",
  },
  {
    key: 21,
    id: "cam-bombas-alimentacion-floculante",
    locationId: "operador-bombas-alimentacion-floculante",
    title: "Fajas alimentadoras",
    visible: true,
    idArea: "3500-3700",
  },
  {
    key: 22,
    id: "cam-bombas-dosificadoras-floculante",
    locationId: "operador-bombas-dosificadoras-floculante",
    title: "Faja de sacrificio",
    visible: true,
    idArea: "3500-3700",
  },
  {
    key: 23,
    id: "cam-tanques-mezcladores-floculante",
    locationId: "operador-tanques-mezcladores-floculante",
    title: "Pica roca",
    visible: true,
    idArea: "3500-3700",
  },
  {
    key: 24,
    id: "cam-tanques-almacenamiento-floculante",
    locationId: "operador-tanques-almacenamiento-floculante",
    title: "Supresor de polvo",
    visible: true,
    idArea: "3500-3700",
  },
  {
    key: 25,
    id: "cam-compresor-aire-area-concentradora",
    locationId: "operador-compresor-aire-area-concentradora",
    title: "Compresor de aire área concentradora",
    visible: true,
    idArea: "3900-3300",
  },
  {
    key: 26,
    id: "cam-bombas-descarga-agua",
    locationId: "operador-bombas-descarga-agua",
    title: "Bombas de descarga de agua",
    visible: true,
    idArea: "3900-3700",
  },
];

export { areas, subareas, subSubAreas };
