/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

const files = [
  // root
  '/favicon.ico',
  '/manifest.json',
  '/logo192.png',
  '/logo512.png',
   // application assets
   '/assets/imagenes/logo-quellaveco.png',
   '/assets/imagenes/logo-eduverso.png',
   '/assets/imagenes/logo-eduverso-blanco.png',
   '/applications/imagenes/aislamiento_y_bloqueo.png',
   '/applications/imagenes/boton-cerrar.png',
   '/applications/imagenes/click-izquierdo.jpg',
   '/applications/imagenes/espacion_confinados.png',
   '/applications/imagenes/favicon.ico',
   '/applications/imagenes/favicon.png',
   '/applications/imagenes/flecha-siguiente.gif',
   '/applications/imagenes/horizontal-icono.png',
   '/applications/imagenes/inferior.jpg',
   '/applications/imagenes/intermedia.jpg',
   '/applications/imagenes/llave.png',
   '/applications/imagenes/logo-eduverso.png',
   '/applications/imagenes/logo-eduverso-blanco.png',
   '/applications/imagenes/logo-quellaveco.png',
   '/applications/imagenes/paso1.png',
   '/applications/imagenes/paso2.png',
   '/applications/imagenes/paso3.png',
   '/applications/imagenes/rueda.jpg',
   '/applications/imagenes/superior.jpg',
   '/applications/imagenes/trabajos_en_altura.png',
   '/applications/imagenes/trabajos_en_caliente_1.png',
   '/applications/imagenes/trabajos_en_caliente_2.png',
   '/applications/imagenes/trabajos-confinados-medida-canula-1.png',
   '/applications/imagenes/trabajos-confinados-medida-canula-2.png',
   '/applications/imagenes/trabajos-confinados-medida-canula-3.png',

   '/applications/imagenes/espacios-menu.png',
   '/applications/imagenes/caliente-menu.png',
   '/applications/imagenes/altura-menu.png',
   '/applications/imagenes/aislamiento-menu.png',
   
   '/applications/styles/buttons copy.css',
   '/applications/styles/buttons.css',
   '/applications/styles/checklist copy.css',
   '/applications/styles/checklist.css',
   '/applications/styles/etiquetas.css',
   '/applications/styles/info.css',
   '/applications/styles/notas copy 2.css',
   '/applications/styles/notas copy.css',
   '/applications/styles/notas.css',
   '/applications/styles/notas-img.css',
   '/applications/styles/preloader.css',
   '/applications/styles/quiz.css',
   '/applications/styles/recomendation.css',

   '/applications/audios/Feeder.mp3',

  // Aislamiento y bloqueo
  '/applications/Aislamiento_y_bloqueo/Aislamiento y bloqueo.html',
  '/applications/Aislamiento_y_bloqueo/Lototo.css',
  '/applications/Aislamiento_y_bloqueo/Lototo.js',
  '/applications/Aislamiento_y_bloqueo/Lototo.max',
  '/applications/Aislamiento_y_bloqueo/Lototo.gltf',
  '/applications/Aislamiento_y_bloqueo/Lototo.bin.xz',
  '/applications/Aislamiento_y_bloqueo/Lototo.bin',
  '/applications/Aislamiento_y_bloqueo/Lototo.gltf.xz',
  '/applications/Aislamiento_y_bloqueo/v3d.js',
  '/applications/Aislamiento_y_bloqueo/visual_logic.js',

  '/applications/Aislamiento_y_bloqueo/001.jpg',
  '/applications/Aislamiento_y_bloqueo/001b.jpg',
  '/applications/Aislamiento_y_bloqueo/1_EpuntoN1_Edu_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/002.jpg',
  '/applications/Aislamiento_y_bloqueo/2_CandadoSG_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/alimentador_1_mtl_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/aluminioSpecular.jpg',
  '/applications/Aislamiento_y_bloqueo/Amarillo.jpg',
  '/applications/Aislamiento_y_bloqueo/Apronfeeder.jpg',
  '/applications/Aislamiento_y_bloqueo/AzulAcero.jpg',
  '/applications/Aislamiento_y_bloqueo/barra.jpg',
  '/applications/Aislamiento_y_bloqueo/base_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/base_color.jpg',
  '/applications/Aislamiento_y_bloqueo/base_normal.jpg',
  '/applications/Aislamiento_y_bloqueo/brazo_1_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/brazo_1_normal.jpg',
  '/applications/Aislamiento_y_bloqueo/brazo_2_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/brazo_2_normal.jpg',
  '/applications/Aislamiento_y_bloqueo/Caja de bloqueo.jpg',
  '/applications/Aislamiento_y_bloqueo/caja_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/caja_extin_FireExtinguisher_Extinguisher_SG1_BaseMap.jpg',
  '/applications/Aislamiento_y_bloqueo/caja_normal.jpg',
  '/applications/Aislamiento_y_bloqueo/cara03.jpg',
  '/applications/Aislamiento_y_bloqueo/cascoD_BaseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/cascoD_Normal.jpg',
  '/applications/Aislamiento_y_bloqueo/Cemento08.jpg',
  '/applications/Aislamiento_y_bloqueo/chancador_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/chancador_normal.jpg',
  '/applications/Aislamiento_y_bloqueo/chutes_3_mtl_baseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/colector_de_polvo_ao.jpg',
  '/applications/Aislamiento_y_bloqueo/concrete_b_Albedo.jpg',
  '/applications/Aislamiento_y_bloqueo/Concreto105.jpg',
  '/applications/Aislamiento_y_bloqueo/CorrugadoCafe.jpg',
  '/applications/Aislamiento_y_bloqueo/cuerpo tablero plano.jpg',
  '/applications/Aislamiento_y_bloqueo/Electroiman.jpg',
  '/applications/Aislamiento_y_bloqueo/Epps.png',
  '/applications/Aislamiento_y_bloqueo/estanteepps_BaseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/estanteepps_Normal.jpg',
  '/applications/Aislamiento_y_bloqueo/Etiqueta 00.jpg',
  '/applications/Aislamiento_y_bloqueo/Etiqueta 01.jpg',
  '/applications/Aislamiento_y_bloqueo/Etiqueta 02.jpg',
  '/applications/Aislamiento_y_bloqueo/ExtintorLetrero.png',
  '/applications/Aislamiento_y_bloqueo/Foco boton.jpg',
  '/applications/Aislamiento_y_bloqueo/Foco boton2.jpg',
  '/applications/Aislamiento_y_bloqueo/Foco emergencia.jpg',
  '/applications/Aislamiento_y_bloqueo/Foco rojo.jpg',
  '/applications/Aislamiento_y_bloqueo/Foco verde.jpg',
  '/applications/Aislamiento_y_bloqueo/franja.jpg',
  '/applications/Aislamiento_y_bloqueo/gabineteElecUV_BaseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/gabineteElecUV_Normal.jpg',
  '/applications/Aislamiento_y_bloqueo/gravel_b_Albedo.jpg',
  '/applications/Aislamiento_y_bloqueo/kloofendal_48d_partly_cloudy_puresky.png',
  '/applications/Aislamiento_y_bloqueo/Light_02_lp_Material__38_Emissive.png',
  '/applications/Aislamiento_y_bloqueo/Light_02_lp_Material__39_BaseColor.png',
  '/applications/Aislamiento_y_bloqueo/LockoutStation.jpg',
  '/applications/Aislamiento_y_bloqueo/mameluco.png',
  '/applications/Aislamiento_y_bloqueo/melta_corrugado_albedo.jpg',
  '/applications/Aislamiento_y_bloqueo/Negro02.jpg',
  '/applications/Aislamiento_y_bloqueo/.jpg',
  '/applications/Aislamiento_y_bloqueo/.jpg',
  '/applications/Aislamiento_y_bloqueo/Opacity161.jpg',
  '/applications/Aislamiento_y_bloqueo/Pared concreto.jpg',
  '/applications/Aislamiento_y_bloqueo/Pinzas bloqueo.jpg',
  '/applications/Aislamiento_y_bloqueo/Piso concreto.jpg',
  '/applications/Aislamiento_y_bloqueo/piso.jpg',
  '/applications/Aislamiento_y_bloqueo/PisoMetalico2-P.jpg',
  '/applications/Aislamiento_y_bloqueo/PuertaD_BaseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/PuertaS_BaseColor.jpg',
  '/applications/Aislamiento_y_bloqueo/Quellaveco verde pacai.jpg',
  '/applications/Aislamiento_y_bloqueo/RiesgoElectrico1.png',
  '/applications/Aislamiento_y_bloqueo/STC_Boot_DIF512.jpg',
  '/applications/Aislamiento_y_bloqueo/STC_Boot_NM512.jpg',
  '/applications/Aislamiento_y_bloqueo/Toolbox_Diff.jpg',
  '/applications/Aislamiento_y_bloqueo/vigas_normal.jpg',

  '/applications/Aislamiento_y_bloqueo/audios/nota_1.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_2.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_3.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_4.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_5.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_6.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_7.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_8.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_9.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_10.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_10_2.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_11.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_12.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_13.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_14.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_15.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_16.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_17.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_18.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_19.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_20.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_21.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_22.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_23.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_24.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_25.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_26.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_27.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_28.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_29.mp3',  
  '/applications/Aislamiento_y_bloqueo/audios/nota_inicio.mp3',
  '/applications/Aislamiento_y_bloqueo/audios/nota_final.mp3',



   // Espacios_confinados_v01
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.html',
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.css',
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.js',
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.bin.xz',
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.bin',
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.mb',
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.gltf',
   '/applications/Espacios_confinados_v01/Espacios_confinados_v01.gltf.xz',
   '/applications/Espacios_confinados_v01/v3d.js',
   '/applications/Espacios_confinados_v01/visual_logic.js',

    '/applications/Espacios_confinados_v01/aluminioSpecular.jpg',
    '/applications/Espacios_confinados_v01/Amarillo19.jpg',
    '/applications/Espacios_confinados_v01/amarilloCAT.jpg',
    '/applications/Espacios_confinados_v01/AmarilloLCh01.jpg',
    '/applications/Espacios_confinados_v01/AmarilloProtectoresAuditivos.jpg',
    '/applications/Espacios_confinados_v01/AmarilloSintetico.jpg',
    '/applications/Espacios_confinados_v01/Azul sucio_R 01.jpg',
    '/applications/Espacios_confinados_v01/Azul sucio03.jpg',
    '/applications/Espacios_confinados_v01/base color_chutes.jpg',
    '/applications/Espacios_confinados_v01/base color_concreto.jpg',
    '/applications/Espacios_confinados_v01/base color_vigas_1.jpg',
    '/applications/Espacios_confinados_v01/base color_vigas_2.jpg',
    '/applications/Espacios_confinados_v01/base color_vigas_3.jpg',
    '/applications/Espacios_confinados_v01/base color_vigas_4.jpg',
    '/applications/Espacios_confinados_v01/base color_vigas_5.jpg',
    '/applications/Espacios_confinados_v01/base_color_etiqueta_roja.jpg',
    '/applications/Espacios_confinados_v01/base_color_etiqueta_verde.jpg',
    '/applications/Espacios_confinados_v01/ChalecoNaranja.jpg',
    '/applications/Espacios_confinados_v01/Cinta LCh.jpg',
    '/applications/Espacios_confinados_v01/Cobre.jpg',
    '/applications/Espacios_confinados_v01/Cobre07.jpg',
    '/applications/Espacios_confinados_v01/CobreMosqueton.jpg',
    '/applications/Espacios_confinados_v01/Crema17.jpg',
    '/applications/Espacios_confinados_v01/Crema28.jpg',
    '/applications/Espacios_confinados_v01/CremaCasco.jpg',
    '/applications/Espacios_confinados_v01/DefaultMaterial_baseColor.jpg',
    '/applications/Espacios_confinados_v01/estuche_negro_baseColor.jpg',
    '/applications/Espacios_confinados_v01/etiqueta_MSA.jpg',
    '/applications/Espacios_confinados_v01/EtiquetaLineade Vida.jpg',
    '/applications/Espacios_confinados_v01/gris.jpg',
    '/applications/Espacios_confinados_v01/GuantesCuero.jpg',
    '/applications/Espacios_confinados_v01/lambert1_Base_Color_AO.jpg',
    '/applications/Espacios_confinados_v01/lambert1_Metallic_1001.jpg',
    '/applications/Espacios_confinados_v01/lambert1_Normal_OpenGL_1001.jpg',
    '/applications/Espacios_confinados_v01/lambert1_Roughness_1001.jpg',
    '/applications/Espacios_confinados_v01/Mameluco.jpg',
    '/applications/Espacios_confinados_v01/Minero ConEPP 01 (hombre canoso).jpg',
    '/applications/Espacios_confinados_v01/multigas_base_color.jpg',
    '/applications/Espacios_confinados_v01/multigas_cuerda_base_color.jpg',
    '/applications/Espacios_confinados_v01/multigas_medidor_base_color.jpg',
    '/applications/Espacios_confinados_v01/Negro02.jpg',
    '/applications/Espacios_confinados_v01/Negropersona.jpg',
    '/applications/Espacios_confinados_v01/Ojos01.jpg',
    '/applications/Espacios_confinados_v01/Pastico25.jpg',
    '/applications/Espacios_confinados_v01/Rejilla01.jpg',
    '/applications/Espacios_confinados_v01/Rojo19.jpg',
    '/applications/Espacios_confinados_v01/RojoLCh.jpg',
    '/applications/Espacios_confinados_v01/Shiny Hdri Skies.jpg',
    '/applications/Espacios_confinados_v01/SinteticoNegro.jpg',
    '/applications/Espacios_confinados_v01/SinteticoRojo.jpg',
    '/applications/Espacios_confinados_v01/sistema_de_concentrado_baseColor.jpg',
    '/applications/Espacios_confinados_v01/sistema_lavador_de_gases_baseColor.jpg',
    '/applications/Espacios_confinados_v01/Tejido17.png',
    '/applications/Espacios_confinados_v01/Toolbox_Diff.jpg',
    '/applications/Espacios_confinados_v01/vigas_normal.jpg',
    '/applications/Espacios_confinados_v01/ZapatosCafes.jpg',

    '/applications/Espacios_confinados_v01/audios/nota_1.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_2.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_2_1.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_3.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_4.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_5.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_5_1.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_5_2.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_6.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_6_1.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_6_2.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_7.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_7_1.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_7_2.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_8.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_9.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_inicio.mp3',
    '/applications/Espacios_confinados_v01/audios/nota_final.mp3',

     // Trabajos_en_altura
     '/applications/Trabajos_en_altura/Trabajos_en_altura.html',
     '/applications/Trabajos_en_altura/Trabajos_en_altura.css',
     '/applications/Trabajos_en_altura/Trabajos_en_altura.js',
     '/applications/Trabajos_en_altura/Trabajos_en_altura.bin.xz',
     '/applications/Trabajos_en_altura/Trabajos_en_altura.bin',
     '/applications/Trabajos_en_altura/Trabajos_en_altura.blend',
     '/applications/Trabajos_en_altura/Trabajos_en_altura.gltf',
     '/applications/Trabajos_en_altura/Trabajos_en_altura.gltf.xz',
     '/applications/Trabajos_en_altura/v3d.js',
     '/applications/Trabajos_en_altura/visual_logic.js',

     '/applications/Trabajos_en_altura/aluminioSpecular.jpg',
     '/applications/Trabajos_en_altura/amarilloCAT.jpg',
     '/applications/Trabajos_en_altura/AmarilloLCh01.jpg',
     '/applications/Trabajos_en_altura/AmarilloProtectoresAuditivos.jpg',
     '/applications/Trabajos_en_altura/AmarilloSintetico.jpg',
     '/applications/Trabajos_en_altura/Azul sucio_R 01.jpg',
     '/applications/Trabajos_en_altura/Azul sucio03.jpg',
     '/applications/Trabajos_en_altura/base color_chutes.jpg',
     '/applications/Trabajos_en_altura/base color_concreto.jpg',
     '/applications/Trabajos_en_altura/base color_vigas_1.jpg',
     '/applications/Trabajos_en_altura/base color_vigas_2.jpg',
     '/applications/Trabajos_en_altura/base color_vigas_3.jpg',
     '/applications/Trabajos_en_altura/base_color_etiqueta_roja.jpg',
     '/applications/Trabajos_en_altura/base_color_etiqueta_verde.jpg',
     '/applications/Trabajos_en_altura/ChalecoNaranja.jpg',
     '/applications/Trabajos_en_altura/Cinta LCh.jpg',
     '/applications/Trabajos_en_altura/Cobre.jpg',
     '/applications/Trabajos_en_altura/CobreMosqueton.jpg',
     '/applications/Trabajos_en_altura/Crema28.jpg',
     '/applications/Trabajos_en_altura/CremaCasco.jpg',
     '/applications/Trabajos_en_altura/DefaultMaterial_baseColor.jpg',
     '/applications/Trabajos_en_altura/etiqueta_MSA.jpg',
     '/applications/Trabajos_en_altura/EtiquetaLineade Vida.jpg',
     '/applications/Trabajos_en_altura/gris.jpg',
     '/applications/Trabajos_en_altura/GuantesCuero.jpg',
     '/applications/Trabajos_en_altura/Mameluco.jpg',
     '/applications/Trabajos_en_altura/Minero ConEPP 01 (hombre canoso).jpg',
     '/applications/Trabajos_en_altura/Negro02.jpg',
     '/applications/Trabajos_en_altura/Negropersona.jpg',
     '/applications/Trabajos_en_altura/Ojos01.jpg',
     '/applications/Trabajos_en_altura/Opacity andamio.jpg',
     '/applications/Trabajos_en_altura/Rejilla01.jpg',
     '/applications/Trabajos_en_altura/RojoLCh.jpg',
     '/applications/Trabajos_en_altura/Shiny Hdri Skies.jpg',
     '/applications/Trabajos_en_altura/SinteticoNegro.jpg',
     '/applications/Trabajos_en_altura/SinteticoNegro_claro.jpg',
     '/applications/Trabajos_en_altura/SinteticoRojo.jpg',
     '/applications/Trabajos_en_altura/sistema_de_concentrado_baseColor.jpg',
     '/applications/Trabajos_en_altura/sistema_lavador_de_gases_baseColor.jpg',
     '/applications/Trabajos_en_altura/Tejido17.png',
     '/applications/Trabajos_en_altura/Toolbox_Diff.jpg',
     '/applications/Trabajos_en_altura/vigas_normal.jpg',
     '/applications/Trabajos_en_altura/ZapatosCafes.jpg',

     '/applications/Trabajos_en_altura/audios/nota_1.mp3',
     '/applications/Trabajos_en_altura/audios/nota_2.mp3',
     '/applications/Trabajos_en_altura/audios/nota_3.mp3',
     '/applications/Trabajos_en_altura/audios/nota_4.mp3',
     '/applications/Trabajos_en_altura/audios/nota_5.mp3',
     '/applications/Trabajos_en_altura/audios/nota_5_1.mp3',
     '/applications/Trabajos_en_altura/audios/nota_5_2.mp3',
     '/applications/Trabajos_en_altura/audios/nota_5_3.mp3',
     '/applications/Trabajos_en_altura/audios/nota_5_4.mp3',
     '/applications/Trabajos_en_altura/audios/nota_5_5.mp3',
     '/applications/Trabajos_en_altura/audios/nota_6.mp3',
     '/applications/Trabajos_en_altura/audios/nota_6_1.mp3',
     '/applications/Trabajos_en_altura/audios/nota_6_2.mp3',
     '/applications/Trabajos_en_altura/audios/nota_6_3.mp3',
     '/applications/Trabajos_en_altura/audios/nota_6_4.mp3',
     '/applications/Trabajos_en_altura/audios/nota_6_5.mp3',
     '/applications/Trabajos_en_altura/audios/nota_7.mp3',
     '/applications/Trabajos_en_altura/audios/nota_8.mp3',
     '/applications/Trabajos_en_altura/audios/nota_final.mp3',
     '/applications/Trabajos_en_altura/audios/nota_inicio.mp3',

     
      // Trabajos_en_caliente
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.html',
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.css',
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.js',
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.bin.xz',
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.bin',
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.mb',
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.gltf',
      '/applications/Trabajos_en_caliente/Trabajos_en_caliente.gltf.xz',
      '/applications/Trabajos_en_caliente/v3d.js',
      '/applications/Trabajos_en_caliente/visual_logic.js',

      '/applications/Trabajos_en_caliente/0000029DC665E0B8.jpg',
      '/applications/Trabajos_en_caliente/alimentador_1_mtl_baseColor.jpg',
      '/applications/Trabajos_en_caliente/alimentador_1_mtl_normal.jpg',
      '/applications/Trabajos_en_caliente/alimentador_1_mtl_occlusionRoughnessMetallic.jpg',
      '/applications/Trabajos_en_caliente/AmarilloLCh01.jpg',
      '/applications/Trabajos_en_caliente/base_color.jpg',
      '/applications/Trabajos_en_caliente/biombo_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/biombo_Metalness.jpg',
      '/applications/Trabajos_en_caliente/biombo_Normal.jpg',
      '/applications/Trabajos_en_caliente/biombo_Roughness.jpg',
      '/applications/Trabajos_en_caliente/bota_bota_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/bota_bota_Normal.jpg',
      '/applications/Trabajos_en_caliente/bota_bota_Roughness.jpg',
      '/applications/Trabajos_en_caliente/caja_meta.jpg',
      '/applications/Trabajos_en_caliente/cara.jpg',
      '/applications/Trabajos_en_caliente/casco_careta_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/casco_careta_Metalness.jpg',
      '/applications/Trabajos_en_caliente/casco_careta_Roughness.jpg',
      '/applications/Trabajos_en_caliente/casco_casco_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/casco_casco_Roughness.jpg',
      '/applications/Trabajos_en_caliente/chancador_baseColor.jpg',
      '/applications/Trabajos_en_caliente/chancador_normal.jpg',
      '/applications/Trabajos_en_caliente/chancador_occlusionRoughnessMetallic.jpg',
      '/applications/Trabajos_en_caliente/cilindro_cilindro_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/cilindro_cilindro_Metalness.jpg',
      '/applications/Trabajos_en_caliente/cilindro_cilindro_Roughness.jpg',
      '/applications/Trabajos_en_caliente/Cinta LCh.jpg',
      '/applications/Trabajos_en_caliente/concrete_b_Albedo.jpg',
      '/applications/Trabajos_en_caliente/concrete_b_Normal.jpg',
      '/applications/Trabajos_en_caliente/concrete_b_Roughness.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_L_mat_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_L_mat_Metalness.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_L_mat_Normal.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_L_mat_Roughness.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_R_mat_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_R_mat_Metalness.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_R_mat_Normal.jpg',
      '/applications/Trabajos_en_caliente/guantes_guante_R_mat_Roughness.jpg',
      '/applications/Trabajos_en_caliente/GuantesCuero.jpg',
      '/applications/Trabajos_en_caliente/Jebe05.jpg',
      '/applications/Trabajos_en_caliente/Madera26.jpg',
      '/applications/Trabajos_en_caliente/Mameluco.jpg',
      '/applications/Trabajos_en_caliente/mandil_mandil_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/mandil_mandil_Normal.jpg',
      '/applications/Trabajos_en_caliente/mandil_mandil_Roughness.jpg',
      '/applications/Trabajos_en_caliente/mask_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/mask_Normal.jpg',
      '/applications/Trabajos_en_caliente/MetalDes090.jpg',
      '/applications/Trabajos_en_caliente/Minero ConEPP 01 (hombre canoso).jpg',
      '/applications/Trabajos_en_caliente/Negropersona.jpg',
      '/applications/Trabajos_en_caliente/Ojos01.jpg',
      '/applications/Trabajos_en_caliente/PisoMetalico2-P.jpg',
      '/applications/Trabajos_en_caliente/rejas.jpg',
      '/applications/Trabajos_en_caliente/RojoLCh.jpg',
      '/applications/Trabajos_en_caliente/Ropa.jpg',
      '/applications/Trabajos_en_caliente/ropav2_mameluco_mat_Normal.jpg',
      '/applications/Trabajos_en_caliente/ropav2_mameluco_mat_Roughness.jpg',
      '/applications/Trabajos_en_caliente/roughImp_130.jpg',
      '/applications/Trabajos_en_caliente/roughness_map.jpg',
      '/applications/Trabajos_en_caliente/rugnes.jpg',
      '/applications/Trabajos_en_caliente/tanke_tanke_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/tanke_tanke_Metalness.jpg',
      '/applications/Trabajos_en_caliente/tanke_tanke_Normal.jpg',
      '/applications/Trabajos_en_caliente/tanke_tanke_Roughness.jpg',
      '/applications/Trabajos_en_caliente/tapon_tapon1_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/tapon_tapon1_Roughness.jpg',
      '/applications/Trabajos_en_caliente/tapon_tapon2_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/tapon_tapon2_Roughness.jpg',
      '/applications/Trabajos_en_caliente/Toolbox_Diff.jpg',
      '/applications/Trabajos_en_caliente/trajv2_mameluco_mat_BaseColor.jpg',
      '/applications/Trabajos_en_caliente/trajv2_mameluco_mat_Metalness.jpg',
      '/applications/Trabajos_en_caliente/trajv2_mameluco_mat_Normal.jpg',
      '/applications/Trabajos_en_caliente/trajv2_mameluco_mat_Roughness.jpg',
      '/applications/Trabajos_en_caliente/vigas_normal.jpg',
      '/applications/Trabajos_en_caliente/ZapatosCafes.jpg',

      '/applications/Trabajos_en_caliente/audios/nota_1.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_2.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_3.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_4.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_5.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_6.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_7.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_inicio.mp3',
      '/applications/Trabajos_en_caliente/audios/nota_final.mp3',
     

];

const filesPrecache = files.map(url => ({ url, revision: null }));

precacheAndRoute(filesPrecache);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.jpg'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'imagesjpg2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.js'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'scripts2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.xz'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'visual2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.html'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'Hypertext2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.mp3'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new CacheFirst({
    cacheName: 'Audios2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.css'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'Styles2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Cache all files in the public directory
/* registerRoute(
  // Match all files in the public directory
  ({ request }) => request.url.startsWith(self.location.origin + '/public/applications/'),
  // Use CacheFirst strategy to cache files and serve them from cache if available
  new StaleWhileRevalidate({
    cacheName: 'PublicFiles2',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used files are removed.
      new ExpirationPlugin({ maxEntries: 100 }),
    ],
  })
); */

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});


/* self.addEventListener('install', event => {
  console.log('Service Worker instalado');
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      console.log('Caché abierta correctamente');
      return cache.addAll([
        // root
        '/',
        '/index.html',
        '/favicon.ico',
        '/manifest.json',
        '/logo192.png',
        '/logo512.png',
        // application assets
        '/assets/imagenes/logo-quellaveco.png',
        '/assets/imagenes/logo-eduverso.png',
        '/assets/imagenes/logo-eduverso-blanco.png',
        '/applications/images/advertencia.png',
        '/applications/images/click-izquierdo.png',
        '/applications/images/derecho.png',
        '/applications/images/paso1.png',
        '/applications/images/paso2.png',
        '/applications/images/paso3.png',
        '/applications/images/rueda.png',
        '/applications/images/tecla.png',
        '/applications/styles.css',
        '/applications/audios/area-1000-parte-a.mp3',
        '/applications/audios/area-1000-parte-b.mp3',
        '/applications/audios/area-2000-faja.mp3',
        '/applications/audios/area-2000.mp3',
        '/applications/audios/area-3000-parte-a.mp3',
        '/applications/audios/area-3000-parte-b.mp3',
        '/applications/audios/area-3000-parte-c.mp3',
        '/applications/audios/area-3300-1.mp3',
        '/applications/audios/area-3300.mp3',
        '/applications/audios/area-4000-parte-a.mp3',
        '/applications/audios/area-4000-parte-b.mp3',
        '/applications/audios/area-4000-parte-c.mp3',
        '/applications/audios/area-4000-parte-d.mp3',
        '/applications/audios/area-4000-parte-e.mp3',
        '/applications/audios/area-4000.mp3',
        '/applications/audios/area-5800.mp3',
        '/applications/audios/bienvenido-2.mp3',
        '/applications/audios/bienvenido-completo.mp3',
        '/applications/audios/bienvenido.mp3',
        // 0000General
        '/applications/0000General/0000General.html',
        '/applications/0000General/0000General.css',
        '/applications/0000General/0000General.js',
        '/applications/0000General/0000General.bin.xz',
        '/applications/0000General/0000General.bin',
        '/applications/0000General/0000General.blend',
        '/applications/0000General/0000General.gltf',
        '/applications/0000General/0000General.gltf.xz',
        '/applications/0000General/0000General.v3d.js',
        '/applications/0000General/0000General.visual_logic.js',
        // 2600Chancado01
        '/applications/2600Chancado01/2600Chancado01.html',
        '/applications/2600Chancado01/2600Chancado01.css',
        '/applications/2600Chancado01/2600Chancado01.js',
        '/applications/2600Chancado01/2600Chancado01.bin.xz',
        '/applications/2600Chancado01/2600Chancado01.bin',
        '/applications/2600Chancado01/2600Chancado01.blend',
        '/applications/2600Chancado01/2600Chancado01.gltf',
        '/applications/2600Chancado01/2600Chancado01.gltf.xz',
        '/applications/2600Chancado01/2600Chancado01.v3d.js',
        '/applications/2600Chancado01/2600Chancado01.visual_logic.js',
        // 3100molienda
        '/applications/3100molienda/3100molienda.html',
        '/applications/3100molienda/3100molienda.css',
        '/applications/3100molienda/3100molienda.js',
        '/applications/3100molienda/3100molienda.bin.xz',
        '/applications/3100molienda/3100molienda.bin',
        '/applications/3100molienda/3100molienda.blend',
        '/applications/3100molienda/3100molienda.gltf',
        '/applications/3100molienda/3100molienda.gltf.xz',
        '/applications/3100molienda/3100molienda.v3d.js',
        '/applications/3100molienda/3100molienda.visual_logic.js',
        // 3300Flotacion
        '/applications/3300Flotacion/3300Flotacion.html',
        '/applications/3300Flotacion/3300Flotacion.css',
        '/applications/3300Flotacion/3300Flotacion.js',
        '/applications/3300Flotacion/3300Flotacion.bin.xz',
        '/applications/3300Flotacion/3300Flotacion.bin',
        '/applications/3300Flotacion/3300Flotacion.blend',
        '/applications/3300Flotacion/3300Flotacion.gltf',
        '/applications/3300Flotacion/3300Flotacion.gltf.xz',
        '/applications/3300Flotacion/3300Flotacion.v3d.js',
        '/applications/3300Flotacion/3300Flotacion.visual_logic.js',
        // 4000Relaves
        '/applications/4000Relaves/4000Relaves.html',
        '/applications/4000Relaves/4000Relaves.css',
        '/applications/4000Relaves/4000Relaves.js',
        '/applications/4000Relaves/4000Relaves.bin.xz',
        '/applications/4000Relaves/4000Relaves.bin',
        '/applications/4000Relaves/4000Relaves.blend',
        '/applications/4000Relaves/4000Relaves.gltf',
        '/applications/4000Relaves/4000Relaves.gltf.xz',
        '/applications/4000Relaves/4000Relaves.v3d.js',
        '/applications/4000Relaves/4000Relaves.visual_logic.js',
        // 5000Puerto
        '/applications/5000Puerto/5000Puerto.html',
        '/applications/5000Puerto/5000Puerto.css',
        '/applications/5000Puerto/5000Puerto.js',
        '/applications/5000Puerto/5000Puerto.bin.xz',
        '/applications/5000Puerto/5000Puerto.bin',
        '/applications/5000Puerto/5000Puerto.blend',
        '/applications/5000Puerto/5000Puerto.gltf',
        '/applications/5000Puerto/5000Puerto.gltf.xz',
        '/applications/5000Puerto/5000Puerto.v3d.js',
        '/applications/5000Puerto/5000Puerto.visual_logic.js',
      ]);
    }).catch(error => {
      console.error('Error al abrir la caché:', error);
    })
  );
});

self.addEventListener('activate', event => {
  console.log('Service Worker activado');
  event.waitUntil(
    caches.keys().then(cacheNames => {
      // Elimina las cachés antiguas (excepto la caché actual)
      return Promise.all(
        cacheNames.filter(cacheName => {
          return cacheName !== CACHE_NAME;
        }).map(cacheName => {
          return caches.delete(cacheName);
        })
      );
    })
  );
});

self.addEventListener('fetch', event => {
  console.log('Solicitud fetch interceptada:', event.request.url);
  event.respondWith(handleFetch(event.request));
});

async function handleFetch(request:any) {
  try {
    // Intenta obtener la respuesta desde la caché
    const cachedResponse = await caches.match(request);

    // Si la respuesta está en caché, devuélvela
    if (cachedResponse) {
      console.log('Recurso encontrado en caché:', request.url);
      return cachedResponse;
    }

    // Si la respuesta no está en caché, haz la solicitud a la red
    const networkResponse = await fetch(request);

    // Abre el caché y almacena la respuesta de la red para futuras solicitudes
    const cache = await caches.open(CACHE_NAME);
    cache.put(request, networkResponse.clone());
    console.log('Recurso no encontrado en caché, solicitando a la red:', request.url);
    // Devuelve la respuesta de la red
    return networkResponse;
  } catch (error) {
    // Si hay un error al recuperar recursos, puedes manejarlo aquí
    console.error('Error en la solicitud:', error);
    // Devuelve una respuesta predeterminada o una página de error personalizada si es necesario
    return new Response('Error: Recurso no disponible', { status: 500, statusText: 'Internal Server Error' });
  }
} */
